### ISSUE TITLE
useStaticQuery broken 

### ISSUE THREAD

**Issue by fabienheureux** [NathHorrigan/gatsby-source-wagtail#10]
Following Slack's dm with @NathHorrigan, gatsby-source-wagtail breaks useStaticQuery hook. 
The fix can be pulled from https://github.com/birkir/gatsby-source-graphql-universal/commit/a68e20d0cad230a778928809300959a95a536788#diff-6ad5ff1468daded9b3e80d9db6782084 

Will submit a PR later today / next week trying to fix this.

**Comment by fabienheureux** [comment]
Fixed by https://github.com/NathHorrigan/gatsby-source-wagtail/pull/11

**Comment by jimbofreedman** [comment]
@fabienheureux I'm using your PR but am still seeing useStaticQuery errors on the starter site. Is there any other dependency you needed to change?

**Comment by tbrlpld** [comment]
Same issue here. I still get the same error although I have installed the package with the merge commit as the version.

**Comment by fabienheureux** [comment]
This PR need a bit of work actually.
Did you have any other errors ? (murmurhash related, for example)

**Comment by NathHorrigan** [comment]
I’ve actually got this fixed in another branch!

**Comment by NathHorrigan** [comment]
@fabienheureux @tbrlpld  @jimbofreedman 

There will be a new NPM release in the next day which will fix `useStaticQuery` and allow Gatsby to download Wagtail images and process them via Sharp/Gatsby Image.

**Comment by tbrlpld** [comment]
Just tried it out. Works like a charm 👏 

Thank you very much for this update.

**Comment by NathHorrigan** [comment]
No Worries. Closing.
